"""
Auto-generates a C++ source file that embeds a zlib-compressed binary blob.

Usage: python embed_reference.py <input_file> <output.cpp>

The output format matches the C++ embed_reference.cpp tool exactly:
  namespace spring {
    const unsigned char kEmbeddedReference[] = { ... };
    const std::size_t kEmbeddedReferenceCompressedSize = ...;
    const std::size_t kEmbeddedReferenceUncompressedSize = ...;
  }

Python's zlib.compress() produces standard zlib format (RFC 1950), which is
fully compatible with libdeflate_zlib_decompress used at runtime.
"""

import os
import sys
import zlib


def main() -> None:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input> <output.cpp>", file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]

    with open(input_path, "rb") as f:
        raw_bytes = f.read()

    compressed_bytes = zlib.compress(raw_bytes, level=9)

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    with open(output_path, "w", newline="\n") as f:
        f.write(
            "// Auto-generated by tools/codegen/embed_reference.py" " - do not edit.\n"
        )
        f.write("#include <cstddef>\n")
        f.write("namespace spring {\n")
        f.write("extern const unsigned char kEmbeddedReference[];\n")
        f.write("extern const std::size_t kEmbeddedReferenceCompressedSize;\n")
        f.write("extern const std::size_t kEmbeddedReferenceUncompressedSize;\n")
        f.write("const unsigned char kEmbeddedReference[] = {")

        for i, byte in enumerate(compressed_bytes):
            if i != 0:
                f.write(", ")
            if i % 12 == 0:
                f.write("\n    ")
            f.write(f"0x{byte:02x}")

        if compressed_bytes:
            f.write("\n")
        f.write("};\n")
        f.write(
            f"const std::size_t kEmbeddedReferenceCompressedSize ="
            f" {len(compressed_bytes)};\n"
        )
        f.write(
            f"const std::size_t kEmbeddedReferenceUncompressedSize ="
            f" {len(raw_bytes)};\n"
        )
        f.write("}\n")


if __name__ == "__main__":
    main()
