#include <cstddef>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <vector>

#include <libdeflate.h>

namespace {

std::vector<unsigned char> read_file_bytes(const std::filesystem::path &path) {
  std::ifstream input(path, std::ios::binary);
  if (!input.is_open()) {
    throw std::runtime_error("Failed to open input file: " + path.string());
  }

  return std::vector<unsigned char>((std::istreambuf_iterator<char>(input)),
                                    std::istreambuf_iterator<char>());
}

std::vector<unsigned char>
compress_bytes(const std::vector<unsigned char> &raw_bytes) {
  libdeflate_compressor *compressor = libdeflate_alloc_compressor(12);
  if (compressor == nullptr) {
    throw std::runtime_error(
        "Failed to allocate compressor for embedded reference data.");
  }

  const std::size_t compressed_bound =
      libdeflate_zlib_compress_bound(compressor, raw_bytes.size());
  std::vector<unsigned char> compressed(compressed_bound);
  const std::size_t compressed_size =
      libdeflate_zlib_compress(compressor, raw_bytes.data(), raw_bytes.size(),
                               compressed.data(), compressed.size());
  libdeflate_free_compressor(compressor);

  if (compressed_size == 0) {
    throw std::runtime_error("Failed to compress embedded reference data.");
  }

  compressed.resize(compressed_size);
  return compressed;
}

void write_cpp_source(const std::filesystem::path &output_path,
                      const std::vector<unsigned char> &raw_bytes,
                      const std::vector<unsigned char> &compressed_bytes) {
  std::filesystem::create_directories(output_path.parent_path());

  std::ofstream output(output_path, std::ios::binary | std::ios::trunc);
  if (!output.is_open()) {
    throw std::runtime_error("Failed to open output file: " +
                             output_path.string());
  }

  output << "// Auto-generated by tools/codegen/embed_reference.cpp - do not "
            "edit.\n";
  output << "#include <cstddef>\n";
  output << "namespace spring {\n";
  output << "extern const unsigned char kEmbeddedReference[];\n";
  output << "extern const std::size_t kEmbeddedReferenceCompressedSize;\n";
  output << "extern const std::size_t kEmbeddedReferenceUncompressedSize;\n";
  output << "const unsigned char kEmbeddedReference[] = {";

  for (std::size_t index = 0; index < compressed_bytes.size(); ++index) {
    if (index != 0) {
      output << ", ";
    }
    if (index % 12 == 0) {
      output << "\n    ";
    }

    std::ostringstream byte_literal;
    byte_literal << "0x" << std::hex;
    byte_literal.width(2);
    byte_literal.fill('0');
    byte_literal << static_cast<unsigned int>(compressed_bytes[index]);
    output << byte_literal.str();
  }

  if (!compressed_bytes.empty()) {
    output << "\n";
  }
  output << "};\n";
  output << "const std::size_t kEmbeddedReferenceCompressedSize = "
         << compressed_bytes.size() << ";\n";
  output << "const std::size_t kEmbeddedReferenceUncompressedSize = "
         << raw_bytes.size() << ";\n";
  output << "}\n";
}

} // namespace

int main(int argc, char **argv) {
  if (argc != 3) {
    std::cerr << "Usage: " << argv[0] << " <input> <output.cpp>\n";
    return 1;
  }

  try {
    const std::filesystem::path input_path(argv[1]);
    const std::filesystem::path output_path(argv[2]);
    const std::vector<unsigned char> raw_bytes = read_file_bytes(input_path);
    const std::vector<unsigned char> compressed_bytes =
        compress_bytes(raw_bytes);
    write_cpp_source(output_path, raw_bytes, compressed_bytes);
  } catch (const std::exception &error) {
    std::cerr << error.what() << "\n";
    return 1;
  }

  return 0;
}